### ISSUE TITLE
Merging the different repositories

### ISSUE THREAD

**Issue by EHadoux** [GraylinKim/sc2reader#178]
Hi, 

Is it possible for you to merge in this repository all the stuffs that have been done in the different branches of i.e. ggtracker/sc2reader.
As there are some commits ahead and some behind this master, I'm not quite sure what to do.
Moreover, it would be better, imho, to merge all the plugins in one repo, instead of having some here, some in ggtracker's and some in mine.

Cheers,

Emmanuel

**Comment by nibalizer** [comment]
+1 for consolidating
