### ISSUE TITLE
How to build the ability csv file?

### ISSUE THREAD

**Issue by crorella** [GraylinKim/sc2reader#191]
Hello,

I'm trying to build a file similar to this one https://github.com/GraylinKim/sc2reader/blob/master/sc2reader/data/HotS/24764_abilities.csv but for Heroes of the Storm replays, I know the abilities are referenced by the m_abilityTag value and I was able to map a few heroes abilities manually. I wonder if there is any automated way to do it.

**Comment by dsjoerg** [comment]
This might help you: https://www.dropbox.com/sh/vcva674ijz6o15q/AACx9OqkoLkTZz_vatnzaYTBa/sc2dump.cpp?dl=0

**Comment by crorella** [comment]
thanks!

**Comment by crorella** [comment]
@dsjoerg I was able to modify the script to load the process but I'm having a hard time identifying the values for gameCatalog, cUnitIndex and stringNameOffset. Do you know how to do that?  I see there are some instructions 

> - For Heart of the Swarm:
> -  1. Attach to the process 
> -  2. Make sure that writable is unchecked and executable is fully checked
> -  3. Do an array search for "8b 0d ?? ?? ?? ?? 8b 49"
> -  4. Look for the most common match.
> -  5. The the ?? ?? ?? ?? portion is the bytes in reverse order for the gameCatalog
> -  6. Subtract the base address for the process (which you can get by running this script)
> -  7. Add a new case for this build with that information. cUnitIndex and stringNameOffset generally won't change

But those are specific for SC2... I have a dump of the process and I opened it with a hex editor and was able to find some of the common units/abilities (like CAbil) but I don't know what is the starting point of the game catalog. Any help is appreciated :)

**Comment by dsjoerg** [comment]
No idea.  @mischanix?

**Comment by crorella** [comment]
Just bumping this in case @mischanix knows the answer
