### ISSUE TITLE
Old replay files

### ISSUE THREAD

**Issue by agi1512** [GraylinKim/sc2reader#202]
Hello!
Trying to parse replays from blizzard of version 3.16.1: https://github.com/Blizzard/s2client-proto#replay-packs . Is there any way to run simulations, or to translate events to newer format?
Sadly, i get only these types of events, no 'UnitDoneEvent' or simillar ones:
```
{'AddToControlGroupEvent',
 'BasicCommandEvent',
 'CameraEvent',
 'ControlGroupEvent',
 'DataCommandEvent',
 'GetControlGroupEvent',
 'PlayerLeaveEvent',
 'SelectionEvent',
 'SetControlGroupEvent',
 'TargetPointCommandEvent',
 'TargetUnitCommandEvent',
 'UpdateTargetPointCommandEvent',
 'UpdateTargetUnitCommandEvent',
 'UserOptionsEvent'}
```
Any way to get these replays to work? Maybe i can attach sample replay so you dont have to download entire pack?

**Comment by StoicLoofah** [comment]
Hey, so this is a known issue in that whatever Blizzard did to anonymize/create these replays, it ripped out important data (such as the `UnitDoneEvent`) that appears difficult to recover. You can see the discussion at https://github.com/ggtracker/sc2reader/issues/61

Also, https://github.com/ggtracker/sc2reader is now the official version of ggtracker, so I recommend that you use that version, and if you have any issues, you can file them there

**Comment by agi1512** [comment]
Thanks for the answer! I was installing package via pip, so, i guess it's already ggtracker's version. Seems like whoever anonimized these replays is not a cool guy :(
