### ISSUE TITLE
Export replay as .avi?

### ISSUE THREAD

**Issue by matthewoestreich** [GraylinKim/sc2reader#206]
Is it possible to export the replay as .avi or .mp3 or .mp4?

**Comment by dsjoerg** [comment]
Only the SC2 client itself knows how to turn the replay into pretty graphics.  So you could fire up an SC2 client, play the replay there, and record a video of it.  And if you are skilled in such things, you could automate all those steps.   Years ago there was a website that did all that!

**Comment by dsjoerg** [comment]
Ah yes see https://www.reddit.com/r/starcraft/comments/esghy/is_there_an_easyfree_way_to_convert_the_sc2/

**Comment by dsjoerg** [comment]
And https://fraps.com/

**Comment by matthewoestreich** [comment]
@dsjoerg thank you very much for your response!
